package lockwarm

import (
	"context"
	"net/http"
	"sort"
	"strings"
	"sync"
	"testing"
)

// The fixtures below are trimmed from lock files produced by the real tools — yarn
// 1.22.22, yarn 4.18.0 and pnpm 11.23.0 — so the shapes are theirs and not a guess.

const sampleYarnClassic = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@7.24.7":
  version "7.24.7"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.7.tgz#882fd9e09e8ee324e496bd040401c6f046ef4465"
  integrity sha512-BcYH1CVJBO9tvyIZ2jVeXgSIMvGZ2FDRvDdOIVQyuklNKSsx+eppDEBq/g47Ayw+RqNFE+URvOShmf+f/qwAlA==
  dependencies:
    "@babel/highlight" "^7.24.7"
    picocolors "^1.0.0"

chalk@4.1.2:
  version "4.1.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-4.1.2.tgz#aac4e2b7734a740867aeb16bf02aad556a1e7a01"
  integrity sha512-oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==
  dependencies:
    ansi-styles "^4.1.0"
    supports-color "^7.1.0"

local-thing@file:../local-thing:
  version "1.0.0"
`

const sampleBerry = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 10
  cacheKey: 10c0

"@babel/code-frame@npm:7.24.7":
  version: 7.24.7
  resolution: "@babel/code-frame@npm:7.24.7"
  checksum: 10c0/ab0af539473a9f5aeaac7047e377cb4f4edd255a
  languageName: node
  linkType: hard

"chalk@npm:4.1.2":
  version: 4.1.2
  resolution: "chalk@npm:4.1.2"
  checksum: 10c0/4a1d5b9d8b1b6f7c6f8b8e6e2b2c8b9a1d5b9d8b
  languageName: node
  linkType: hard

"lockfmt@workspace:.":
  version: 0.0.0-use.local
  resolution: "lockfmt@workspace:."
  languageName: unknown
  linkType: soft
`

const samplePNPM = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

importers:

  .:
    dependencies:
      chalk:
        specifier: 4.1.2
        version: 4.1.2

packages:

  '@babel/code-frame@7.24.7':
    resolution: {integrity: sha512-BcYH1CVJBO9tvyIZ2jVeXgSIMvGZ2FDRvDdOIVQyuklNKSsx+eppDEBq/g47Ayw+RqNFE+URvOShmf+f/qwAlA==}
    engines: {node: '>=6.9.0'}

  chalk@4.1.2:
    resolution: {integrity: sha512-oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==}
    engines: {node: '>=10'}

snapshots:

  chalk@4.1.2:
    dependencies:
      ansi-styles: 4.3.0
`

func byName(packages []NPMPackage) map[string]NPMPackage {
	out := make(map[string]NPMPackage, len(packages))
	for _, pkg := range packages {
		out[pkg.Name] = pkg
	}
	return out
}

func TestParseYarnClassicKeepsTheChecksumFragment(t *testing.T) {
	packages, err := ParseYarnClassic(sampleYarnClassic)
	if err != nil {
		t.Fatal(err)
	}
	if len(packages) != 2 {
		t.Fatalf("want 2 registry tarballs, got %d: %+v", len(packages), packages)
	}
	found := byName(packages)
	scoped := found["@babel/code-frame"]
	if scoped.Filename != "code-frame-7.24.7.tgz" {
		t.Errorf("filename = %q", scoped.Filename)
	}
	// Yarn verifies this fragment, so losing it would break the install rather than
	// merely look untidy.
	if scoped.Fragment != "#882fd9e09e8ee324e496bd040401c6f046ef4465" {
		t.Errorf("fragment = %q", scoped.Fragment)
	}
	if scoped.Registry != "https://registry.yarnpkg.com" {
		t.Errorf("registry = %q", scoped.Registry)
	}
	if _, present := found["local-thing"]; present {
		t.Error("a file: dependency is not a registry tarball")
	}
}

func TestRewriteYarnClassicMovesURLsAndKeepsFragments(t *testing.T) {
	packages, err := ParseYarnClassic(sampleYarnClassic)
	if err != nil {
		t.Fatal(err)
	}
	const base = "http://127.0.0.1:8080/global/npm"
	rewritten := RewriteYarnClassic(sampleYarnClassic, packages, base)

	for _, want := range []string{
		`resolved "http://127.0.0.1:8080/global/npm/@babel/code-frame/-/code-frame-7.24.7.tgz#882fd9e09e8ee324e496bd040401c6f046ef4465"`,
		`resolved "http://127.0.0.1:8080/global/npm/chalk/-/chalk-4.1.2.tgz#aac4e2b7734a740867aeb16bf02aad556a1e7a01"`,
	} {
		if !strings.Contains(rewritten, want) {
			t.Errorf("missing from the rewrite:\n  %s", want)
		}
	}
	if strings.Contains(rewritten, "registry.yarnpkg.com") {
		t.Error("a URL was left pointing upstream")
	}
	for _, hash := range []string{
		"sha512-BcYH1CVJBO9tvyIZ2jVeXgSIMvGZ2FDRvDdOIVQyuklNKSsx+eppDEBq/g47Ayw+RqNFE+URvOShmf+f/qwAlA==",
		"sha512-oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==",
	} {
		if !strings.Contains(rewritten, hash) {
			t.Error("an integrity hash did not survive the rewrite")
		}
	}
	if strings.Count(rewritten, "\n") != strings.Count(sampleYarnClassic, "\n") {
		t.Error("the rewrite changed the line count, so it reformatted something")
	}
	// Running it twice must settle, so the command is safe to repeat.
	again, err := ParseYarnClassic(rewritten)
	if err != nil {
		t.Fatal(err)
	}
	if second := RewriteYarnClassic(rewritten, again, base); second != rewritten {
		t.Error("rewriting twice did not settle")
	}
}

func TestParseYarnBerryDerivesTarballsFromDescriptors(t *testing.T) {
	packages, err := ParseYarnBerry(sampleBerry)
	if err != nil {
		t.Fatal(err)
	}
	if len(packages) != 2 {
		t.Fatalf("want 2 registry packages, got %d: %+v", len(packages), packages)
	}
	found := byName(packages)
	scoped := found["@babel/code-frame"]
	if scoped.Version != "7.24.7" || scoped.Filename != "code-frame-7.24.7.tgz" {
		t.Errorf("scoped = %+v", scoped)
	}
	// Berry names no registry, and that is the reason it cannot be rewritten.
	if scoped.URL != "" || scoped.Registry != "" {
		t.Errorf("berry should carry no URL or registry, got %+v", scoped)
	}
	if _, present := found["lockfmt"]; present {
		t.Error("a workspace: resolution is not a registry package")
	}
}

func TestParsePNPMReadsEveryKeyShape(t *testing.T) {
	packages, err := ParsePNPM(samplePNPM)
	if err != nil {
		t.Fatal(err)
	}
	found := byName(packages)
	if len(packages) != 2 {
		t.Fatalf("want 2 packages, got %d: %+v", len(packages), packages)
	}
	if got := found["@babel/code-frame"]; got.Filename != "code-frame-7.24.7.tgz" {
		t.Errorf("scoped = %+v", got)
	}
	if got := found["chalk"]; got.Version != "4.1.2" {
		t.Errorf("chalk = %+v", got)
	}
	// The root importer's keys are specifiers rather than versions, and the snapshots:
	// block repeats the package keys. Neither may add anything.
	if _, present := found["."]; present {
		t.Error("the root importer was read as a package")
	}

	// The older key shapes, which a repository's lock may well still be written in.
	for _, older := range []struct{ name, lock string }{
		{"v6", "lockfileVersion: '6.0'\npackages:\n\n  /chalk@4.1.2:\n    resolution: {integrity: sha512-x}\n"},
		{"v5", "lockfileVersion: 5.4\npackages:\n\n  /chalk/4.1.2:\n    resolution: {integrity: sha512-x}\n"},
	} {
		parsed, err := ParsePNPM(older.lock)
		if err != nil {
			t.Fatalf("%s: %v", older.name, err)
		}
		if len(parsed) != 1 || parsed[0].Name != "chalk" || parsed[0].Version != "4.1.2" {
			t.Errorf("%s parsed as %+v", older.name, parsed)
		}
	}
}

func TestJSParsersRejectEachOthersFormats(t *testing.T) {
	// Pointing -lock at the wrong file is the likeliest mistake, and each parser has to
	// say so rather than quietly find nothing and report success.
	cases := []struct {
		name  string
		parse func(string) ([]NPMPackage, error)
	}{
		{"yarn classic", ParseYarnClassic},
		{"yarn berry", ParseYarnBerry},
		{"pnpm", ParsePNPM},
	}
	for _, c := range cases {
		for _, wrong := range []string{sampleNPMLock, sampleLock, "", "nonsense"} {
			if _, err := c.parse(wrong); err == nil {
				// Only a genuine match may succeed.
				switch {
				case c.name == "yarn classic" && strings.Contains(wrong, "yarn lockfile v1"):
				case c.name == "yarn berry" && strings.Contains(wrong, "__metadata:"):
				case c.name == "pnpm" && strings.HasPrefix(wrong, "lockfileVersion:"):
				default:
					t.Errorf("%s accepted a foreign format: %.30q", c.name, wrong)
				}
			}
		}
	}
}

func TestWarmNPMRequestsPackumentAndTarballForEach(t *testing.T) {
	// Two of the four formats install only if the cache can answer for metadata as well
	// as tarballs, so what gets requested is worth pinning down.
	packages, err := ParsePNPM(samplePNPM)
	if err != nil {
		t.Fatal(err)
	}
	// A second version of one package, to check the packument is asked for once.
	packages = append(packages, NPMPackage{
		Name: "chalk", Version: "5.0.0", Filename: "chalk-5.0.0.tgz",
	})

	var mu sync.Mutex
	var asked []string
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		asked = append(asked, r.URL.Path)
		mu.Unlock()
		w.WriteHeader(http.StatusOK)
	})
	if err := WarmNPM(context.Background(), handler, "global", packages, 4, nil); err != nil {
		t.Fatal(err)
	}
	sort.Strings(asked)
	want := []string{
		"/global/npm/@babel/code-frame",
		"/global/npm/@babel/code-frame/-/code-frame-7.24.7.tgz",
		"/global/npm/chalk",
		"/global/npm/chalk/-/chalk-4.1.2.tgz",
		"/global/npm/chalk/-/chalk-5.0.0.tgz",
	}
	if len(asked) != len(want) {
		t.Fatalf("asked for %v", asked)
	}
	for i := range want {
		if asked[i] != want[i] {
			t.Errorf("asked[%d] = %q, want %q", i, asked[i], want[i])
		}
	}
}
