#!/usr/bin/env bash
# One-command host setup — everything `docker compose up` needs but cannot create
# correctly itself. Idempotent: safe to re-run any time; it never overwrites what
# already exists.
#
#   ./scripts/bootstrap.sh [--no-auth] [extra-cert-hostname-or-IP ...]
#
# By default it also mints the console's break-glass superuser (UI_ROOT_USER +
# a random UI_ROOT_PASSWORD), which turns ON control-plane auth; pass --no-auth
# to skip that and leave the API open (trusted networks only).
#
# Why this must run on the HOST, before `up`:
#   * .env is read by the compose CLI to interpolate docker-compose.yml BEFORE any
#     container starts — no container can populate it for its own run.
#   * a bind-mount source that does not exist when `up` runs is created by the
#     docker daemon as root:root, and the containers (which run as YOU precisely so
#     nothing ends up root-owned) then cannot write into it.
set -euo pipefail
cd "$(dirname "$0")/.."

auth=1
san_args=()
for arg in "$@"; do
  case "$arg" in
    --no-auth) auth=0 ;;
    *) san_args+=("$arg") ;;
  esac
done

# --- 1. .env: the container-side uid/gid mapping (see .env.example) ------------
if [ -f .env ]; then
  echo "==> .env exists — leaving it alone (delete it and re-run to regenerate)"
else
  uid="$(id -u)"; gid="$(id -g)"
  # Rootless Docker / Podman: container root already maps back to this user, and a
  # non-zero uid would land in the subuid range (files you can't even read). Run as
  # 0:0 there instead.
  if docker info --format '{{.SecurityOptions}}' 2>/dev/null | grep -qi rootless; then
    echo "==> rootless engine detected: containers run as 0:0 (maps back to you on disk)"
    uid=0; gid=0
  fi
  cat > .env <<EOF
# Generated by scripts/bootstrap.sh — host-specific, gitignored. Delete and re-run
# the script to regenerate. Optional extras (see .env.example): PKGCACHE_SHUTTLE
# to relocate the shuttle staging dir.
PKGCACHE_UID=$uid
PKGCACHE_GID=$gid
EOF
  chmod 600 .env
  echo "==> wrote .env (PKGCACHE_UID=$uid, PKGCACHE_GID=$gid)"

  # Break-glass console superuser — verified from the environment on every login,
  # never stored anywhere else. Its PRESENCE is what turns control-plane auth on.
  if [ "$auth" -eq 1 ]; then
    root_password="$(openssl rand -hex 16)"
    cat >> .env <<EOF

# Console superuser (presence turns ON control-plane auth). Change the password
# any time; remove both lines to run with the API open (trusted networks only).
UI_ROOT_USER=admin
UI_ROOT_PASSWORD=$root_password
EOF
    echo "==> console auth ON — superuser 'admin', password: $root_password"
    echo "    (saved in .env, shown only here; --no-auth next time to skip)"
  else
    echo "==> --no-auth: control-plane auth left OFF (trusted networks only)"
  fi
fi

# --- 2. bind-mount sources that must pre-exist, host-owned ---------------------
mkdir -p caches shuttle/in shuttle/out
echo "==> ensured ./caches and ./shuttle/{in,out} exist (host-owned)"

# --- 3. TLS material (gen-certs reuses an existing CA; SAN args pass through) --
if [ -f certs/server.key ] && [ -f certs/server.crt ]; then
  echo "==> certs/ already populated — run scripts/gen-certs.sh to add hostnames/IPs"
else
  ./scripts/gen-certs.sh ${san_args[@]+"${san_args[@]}"}
fi

cat <<'EOF'

==> ready. Bring the stack up:
      docker compose --profile online --profile ui up -d              # online side
      OFFLINE=1 docker compose --profile offline --profile ui up -d   # air-gapped side
EOF
