// Package onboarding renders auditable, instance-specific client setup scripts.
package onboarding

import (
	"crypto/sha1" // #nosec G505 -- macOS certificate deletion identifies certificates by SHA-1 thumbprint.
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"net"
	"regexp"
	"strconv"
	"strings"
)

var (
	projectPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`)
	hostPattern    = regexp.MustCompile(`^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$`)
)

// Config is the request-specific data embedded in a generated setup script.
// CAPEM is public certificate material; credentials intentionally are not accepted.
type Config struct {
	Project     string
	Host        string
	UnifiedPort int
	ProxyPort   int
	CAPEM       []byte
}

type prepared struct {
	Config
	Authority string
	URLHost   string
	SHA1      string
	SHA256    string
	PEM       string
}

func prepare(cfg Config) (prepared, error) {
	if !ValidProject(cfg.Project) {
		return prepared{}, fmt.Errorf("invalid project %q", cfg.Project)
	}
	if !ValidHost(cfg.Host) {
		return prepared{}, fmt.Errorf("invalid client-facing host %q", cfg.Host)
	}
	if cfg.UnifiedPort < 1 || cfg.UnifiedPort > 65535 ||
		cfg.ProxyPort < 1 || cfg.ProxyPort > 65535 {
		return prepared{}, fmt.Errorf("invalid client-facing port")
	}
	block, _ := pem.Decode(cfg.CAPEM)
	if block == nil || block.Type != "CERTIFICATE" {
		return prepared{}, fmt.Errorf("CA file does not contain a PEM certificate")
	}
	certificate, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return prepared{}, fmt.Errorf("parse CA certificate: %w", err)
	}
	if !certificate.IsCA {
		return prepared{}, fmt.Errorf("configured certificate is not a CA")
	}
	sha1Sum := sha1.Sum(block.Bytes) // #nosec G401 -- certificate-store identifier, not a security decision.
	sha256Sum := sha256.Sum256(block.Bytes)
	urlHost := cfg.Host
	if strings.Contains(urlHost, ":") {
		urlHost = "[" + urlHost + "]"
	}
	normalizedPEM := strings.TrimSpace(string(pem.EncodeToMemory(block))) + "\n"
	return prepared{
		Config: cfg, Authority: net.JoinHostPort(cfg.Host, strconv.Itoa(cfg.UnifiedPort)),
		URLHost: urlHost, SHA1: upperHex(sha1Sum[:]), SHA256: upperHex(sha256Sum[:]),
		PEM: normalizedPEM,
	}, nil
}

// ValidProject reports whether project is safe to embed in paths and scripts.
func ValidProject(project string) bool {
	return projectPattern.MatchString(project)
}

// ValidHost reports whether host is safe to embed as a DNS name or IP literal.
func ValidHost(host string) bool {
	return net.ParseIP(host) != nil || hostPattern.MatchString(host)
}

func upperHex(value []byte) string {
	return strings.ToUpper(hex.EncodeToString(value))
}

// FingerprintSHA256 returns the conventional colon-separated certificate
// fingerprint operators can compare through an out-of-band channel.
func FingerprintSHA256(caPEM []byte) (string, error) {
	block, _ := pem.Decode(caPEM)
	if block == nil || block.Type != "CERTIFICATE" {
		return "", fmt.Errorf("CA file does not contain a PEM certificate")
	}
	certificate, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return "", fmt.Errorf("parse CA certificate: %w", err)
	}
	if !certificate.IsCA {
		return "", fmt.Errorf("configured certificate is not a CA")
	}
	sum := sha256.Sum256(block.Bytes)
	raw := upperHex(sum[:])
	var formatted strings.Builder
	for i := 0; i < len(raw); i += 2 {
		if i > 0 {
			formatted.WriteByte(':')
		}
		formatted.WriteString(raw[i : i+2])
	}
	return formatted.String(), nil
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func psQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

// Shell renders the Linux/macOS installer.
func Shell(cfg Config) ([]byte, error) {
	p, err := prepare(cfg)
	if err != nil {
		return nil, err
	}
	pypiURL := fmt.Sprintf("https://%s:%d/%s/pypi/root/pypi/+simple/",
		p.URLHost, p.UnifiedPort, p.Project)
	npmURL := fmt.Sprintf("https://%s:%d/%s/npm/", p.URLHost, p.UnifiedPort, p.Project)
	filesURL := fmt.Sprintf("https://%s:%d/%s/files/", p.URLHost, p.UnifiedPort, p.Project)
	proxyURL := fmt.Sprintf("http://%s:%d", p.URLHost, p.ProxyPort)
	if p.Project != "global" {
		proxyURL = fmt.Sprintf("http://%s@%s:%d", p.Project, p.URLHost, p.ProxyPort)
	}

	var b strings.Builder
	fmt.Fprintf(&b, `#!/usr/bin/env bash
set -euo pipefail

# Generated by pkgreg for project %s.
# The embedded CA is public. This script never contains an API or write token.
PROJECT=%s
DEFAULT_HOST=%s
UNIFIED_PORT=%d
PROXY_PORT=%d
CA_SHA1=%s
CA_SHA256=%s
DEFAULT_PYPI_URL=%s
DEFAULT_NPM_URL=%s
DEFAULT_FILES_URL=%s
DEFAULT_APT_PROXY=%s
CA_PEM=$(cat <<'PKGREG_CA_EOF'
%sPKGREG_CA_EOF
)

DRY_RUN=0
MODE=install
CACHE_HOST="$DEFAULT_HOST"
CACHE_IP=""

usage() {
  cat <<'PKGREG_USAGE'
Usage: setup.sh [--dry-run] [--uninstall] [--host NAME] [--cache-ip ADDRESS]

Installs pkgreg's public CA, Docker trust, project tool settings, and optionally
a managed hosts-file entry. Run --dry-run without sudo first. Installation and
uninstallation require an explicit root invocation; this script never invokes sudo.

--host NAME         Override the generated client-facing hostname. The server
                    certificate must contain this name.
--cache-ip ADDRESS  Map NAME to ADDRESS in the machine hosts file.
PKGREG_USAGE
}

while (($#)); do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --uninstall) MODE=uninstall; shift ;;
    --host) [[ $# -ge 2 ]] || { echo "missing value for --host" >&2; exit 2; }; CACHE_HOST="$2"; shift 2 ;;
    --cache-ip) [[ $# -ge 2 ]] || { echo "missing value for --cache-ip" >&2; exit 2; }; CACHE_IP="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ ! "$CACHE_HOST" =~ ^[A-Za-z0-9][A-Za-z0-9.-]*$ && ! "$CACHE_HOST" =~ ^[0-9A-Fa-f:]+$ ]]; then
  echo "invalid --host value" >&2
  exit 2
fi
if [[ -n "$CACHE_IP" && ! "$CACHE_IP" =~ ^[0-9A-Fa-f:.]+$ ]]; then
  echo "invalid --cache-ip value" >&2
  exit 2
fi
if (( ! DRY_RUN )) && [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo "run this script explicitly as root (for example: sudo ./setup.sh)" >&2
  exit 1
fi

URL_HOST="$CACHE_HOST"
[[ "$URL_HOST" == *:* ]] && URL_HOST="[$URL_HOST]"
AUTHORITY="${URL_HOST}:${UNIFIED_PORT}"
INSTALL_ROOT="/etc/pkgreg/projects/${PROJECT}"
SHARED_CA="/etc/pkgreg/authorities/${CA_SHA256}.crt"
STATE_FILE="${INSTALL_ROOT}/state"
ENV_FILE="${INSTALL_ROOT}/env.sh"
# A configuration directory of this project's own, which env.sh puts first in
# XDG_CONFIG_DIRS: uv reads its machine-level uv.toml from there before /etc/uv.
XDG_DIR="${INSTALL_ROOT}/xdg"
UV_CONFIG="${XDG_DIR}/uv/uv.toml"
HOSTS_FILE="/etc/hosts"
HOSTS_MARKER="# pkgreg:${PROJECT}"
PROFILE_MARKER="pkgreg:${PROJECT}"

# Where this platform's Docker daemon reads a per-registry certificate.
#
# These are genuinely different locations, and an earlier version of this script wrote the
# Linux one everywhere — so on macOS the certificate was installed where Docker Desktop
# never looks, the script reported success, and docker pull still failed to verify the
# cache. Docker Desktop reads a directory under the invoking user's home instead, which is
# why this resolves it from SUDO_USER: the script runs as root, and root's home is not
# where Desktop looks.
docker_ca_path() {
  case "$(uname -s)" in
    Linux) printf '/etc/docker/certs.d/%%s/ca.crt' "$AUTHORITY" ;;
    Darwin)
      local home
      home=$(desktop_home) || return 1
      printf '%%s/.docker/certs.d/%%s/ca.crt' "$home" "$AUTHORITY"
      ;;
    *) return 1 ;;
  esac
}

desktop_home() {
  if [[ -n "${SUDO_USER:-}" ]]; then
    local resolved
    resolved=$(eval printf '%%s' "~${SUDO_USER}" 2>/dev/null) || resolved=""
    if [[ -n "$resolved" && -d "$resolved" ]]; then
      printf '%%s' "$resolved"
      return 0
    fi
  fi
  [[ -n "${HOME:-}" ]] && printf '%%s' "$HOME"
}

show_cmd() {
  printf '+'
  printf ' %%q' "$@"
  printf '\n'
}

run() {
  if (( DRY_RUN )); then show_cmd "$@"; else "$@"; fi
}

write_file() {
  local destination="$1" mode="$2" content="$3"
  if (( DRY_RUN )); then
    printf '+ write %%s (mode %%s)\n' "$destination" "$mode"
    return
  fi
  mkdir -p "$(dirname "$destination")"
  local temporary
  temporary=$(mktemp "${destination}.tmp.XXXXXX")
  printf '%%s' "$content" >"$temporary"
  chmod "$mode" "$temporary"
  mv "$temporary" "$destination"
}

strip_marker_lines() {
  local file="$1" marker="$2"
  [[ -f "$file" ]] || return 0
  grep -Fq "$marker" "$file" || return 0
  if (( DRY_RUN )); then
    printf '+ remove lines containing %%q from %%s\n' "$marker" "$file"
    return
  fi
  local temporary
  temporary=$(mktemp "${file}.tmp.XXXXXX")
  awk -v marker="$marker" 'index($0, marker) == 0' "$file" >"$temporary"
  cat "$temporary" >"$file"
  rm -f "$temporary"
}

write_hosts_entry() {
  [[ -n "$CACHE_IP" ]] || return 0
  if (( DRY_RUN )); then
    printf '+ replace %%s entry in %%s with: %%s %%s %%s\n' "$HOSTS_MARKER" "$HOSTS_FILE" "$CACHE_IP" "$CACHE_HOST" "$HOSTS_MARKER"
    return
  fi
  local temporary
  temporary=$(mktemp "${HOSTS_FILE}.tmp.XXXXXX")
  awk -v marker="$HOSTS_MARKER" 'index($0, marker) == 0' "$HOSTS_FILE" >"$temporary"
  printf '%%s %%s %%s\n' "$CACHE_IP" "$CACHE_HOST" "$HOSTS_MARKER" >>"$temporary"
  cat "$temporary" >"$HOSTS_FILE"
  rm -f "$temporary"
}

linux_ca_destination() {
  if command -v update-ca-certificates >/dev/null 2>&1; then
    printf '/usr/local/share/ca-certificates/pkgreg-%%s.crt' "$CA_SHA256"
  elif [[ -d /etc/ca-certificates/trust-source/anchors ]] &&
       command -v update-ca-trust >/dev/null 2>&1; then
    # Current Arch ships update-ca-trust too, but unlike RHEL it reads this tree.
    printf '/etc/ca-certificates/trust-source/anchors/pkgreg-%%s.crt' "$CA_SHA256"
  elif command -v update-ca-trust >/dev/null 2>&1; then
    printf '/etc/pki/ca-trust/source/anchors/pkgreg-%%s.crt' "$CA_SHA256"
  elif command -v trust >/dev/null 2>&1; then
    printf '/etc/ca-certificates/trust-source/anchors/pkgreg-%%s.crt' "$CA_SHA256"
  else
    echo "no supported OS CA update command found" >&2
    return 1
  fi
}

refresh_linux_trust() {
  if command -v update-ca-certificates >/dev/null 2>&1; then
    run update-ca-certificates
  elif command -v update-ca-trust >/dev/null 2>&1; then
    run update-ca-trust extract
  else
    run trust extract-compat
  fi
}

other_project_uses_ca() {
  local state
  for state in /etc/pkgreg/projects/*/state; do
    [[ -f "$state" && "$state" != "$STATE_FILE" ]] || continue
    grep -Fqx "CA_SHA256=${CA_SHA256}" "$state" && return 0
  done
  return 1
}

install_client() {
  local pypi_url npm_url corepack_url files_url apt_proxy env_content state_content uv_content
  pypi_url="https://${URL_HOST}:${UNIFIED_PORT}/${PROJECT}/pypi/root/pypi/+simple/"
  npm_url="https://${URL_HOST}:${UNIFIED_PORT}/${PROJECT}/npm/"
  # corepack appends /<name>/<version> itself.
  corepack_url="https://${URL_HOST}:${UNIFIED_PORT}/${PROJECT}/npm"
  files_url="https://${URL_HOST}:${UNIFIED_PORT}/${PROJECT}/files/"
  apt_proxy="http://${URL_HOST}:${PROXY_PORT}"
  [[ "$PROJECT" != global ]] && apt_proxy="http://${PROJECT}@${URL_HOST}:${PROXY_PORT}"

  write_file "$SHARED_CA" 0644 "$CA_PEM"
  state_content=$(printf 'CA_SHA256=%%s\nAUTHORITY=%%s\nHOST=%%s\n' "$CA_SHA256" "$AUTHORITY" "$CACHE_HOST")
  write_file "$STATE_FILE" 0644 "$state_content"
  # Each case pattern opens with "(": bash 3.2, macOS's, otherwise takes a pattern's ")"
  # inside this heredoc for the end of the command substitution around it.
  env_content=$(cat <<PKGREG_ENV
# Generated by pkgreg for project ${PROJECT}. Remove with setup.sh --uninstall.
export PKGREG_PROJECT='$PROJECT'
export PKGREG_SERVER='https://${AUTHORITY}'
export PKGREG_CA_FILE='$SHARED_CA'
export PKGREG_CA_SHA256='$CA_SHA256'
export PKGREG_DOCKER_REGISTRY='$AUTHORITY'
export PKGREG_GIT_URL='https://${AUTHORITY}/${PROJECT}/git'
export PIP_CERT='$SHARED_CA'
export PIP_INDEX_URL='$pypi_url'
# Both spellings: uv 0.11 renamed UV_NATIVE_TLS, and older releases know only that one.
export UV_NATIVE_TLS='true'
export UV_SYSTEM_CERTS='true'
# uv finds this cache in the uv.toml under the first directory here, for uv pip alone:
# an index set here would reach uv lock and uv sync too. A machine-level uv.toml of this
# machine's own would be shadowed by it, so that one is left in charge.
case ":\${XDG_CONFIG_DIRS:-}:" in
  (*":${XDG_DIR}:"*) ;;
  (*) [ -e /etc/uv/uv.toml ] || [ -e /etc/xdg/uv/uv.toml ] ||
        export XDG_CONFIG_DIRS="${XDG_DIR}:\${XDG_CONFIG_DIRS:-/etc/xdg}" ;;
esac
export NODE_EXTRA_CA_CERTS='$SHARED_CA'
export NPM_CONFIG_CAFILE='$SHARED_CA'
export NPM_CONFIG_REGISTRY='$npm_url'
export PNPM_CONFIG_REGISTRY='$npm_url'
export COREPACK_NPM_REGISTRY='$corepack_url'
export GIT_SSL_CAINFO='$SHARED_CA'
export PKGREG_FILES_URL='$files_url'
export PKGREG_APT_PROXY='$apt_proxy'
PKGREG_ENV
)
  write_file "$ENV_FILE" 0644 "$env_content"
  # uv's pip interface, and nothing else. UV_INDEX_URL in env.sh reached uv's project
  # commands as well: uv lock and uv sync rewrote uv.lock to name this cache, a lock no
  # other machine can use, and uv sync --locked refused one made against PyPI. uv reads a
  # [pip] table for uv pip alone, and only the shells that load env.sh find this one.
  uv_content=$(cat <<PKGREG_UV
# Generated by pkgreg for project ${PROJECT}. Remove with setup.sh --uninstall.
[pip]
index-url = "$pypi_url"
PKGREG_UV
)
  write_file "$UV_CONFIG" 0644 "$uv_content"
  local machine_uv
  for machine_uv in /etc/uv/uv.toml /etc/xdg/uv/uv.toml; do
    [[ -e "$machine_uv" ]] || continue
    printf 'note: %%s stays in charge of uv on this machine; for uv pip to use the cache, add index-url = "%%s" to its [pip] table\n' "$machine_uv" "$pypi_url" >&2
    break
  done
  local docker_ca
  if docker_ca=$(docker_ca_path); then
    write_file "$docker_ca" 0644 "$CA_PEM"
  else
    printf 'note: no known Docker certificate directory for this platform; skipping Docker trust\n' >&2
  fi
  write_hosts_entry

	case "$(uname -s)" in
    Linux)
      local ca_destination
      ca_destination=$(linux_ca_destination)
      write_file "$ca_destination" 0644 "$CA_PEM"
      refresh_linux_trust
      local profile_content
      printf -v profile_content "[ -r '%%s' ] && . '%%s'\n" "$ENV_FILE" "$ENV_FILE"
      write_file "/etc/profile.d/pkgreg-${PROJECT}.sh" 0644 "$profile_content"
      ;;
    Darwin)
      if (( DRY_RUN )); then
        show_cmd security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$SHARED_CA"
      else
        security delete-certificate -Z "$CA_SHA1" /Library/Keychains/System.keychain >/dev/null 2>&1 || true
        security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$SHARED_CA"
      fi
      strip_marker_lines /etc/zprofile "$PROFILE_MARKER"
      if (( DRY_RUN )); then
        printf '+ append source line tagged %%s to /etc/zprofile\n' "$PROFILE_MARKER"
      else
        printf '[ -r %%q ] && . %%q # %%s\n' "$ENV_FILE" "$ENV_FILE" "$PROFILE_MARKER" >>/etc/zprofile
      fi
      ;;
    *) echo "unsupported operating system: $(uname -s)" >&2; exit 1 ;;
  esac
  echo "pkgreg client setup installed for project ${PROJECT}."
  echo "Start a login shell, or run: source ${ENV_FILE}"
  echo "CA SHA-256: ${CA_SHA256}"
}

uninstall_client() {
  local shared=0
  other_project_uses_ca && shared=1
  strip_marker_lines "$HOSTS_FILE" "$HOSTS_MARKER"
  strip_marker_lines /etc/zprofile "$PROFILE_MARKER"
  run rm -f "/etc/profile.d/pkgreg-${PROJECT}.sh"
  run rm -f "$ENV_FILE" "$STATE_FILE" "$UV_CONFIG"
  run rmdir "${XDG_DIR}/uv" "$XDG_DIR" 2>/dev/null || true
  run rmdir "$INSTALL_ROOT" 2>/dev/null || true

  if (( ! shared )); then
    local docker_ca
    if docker_ca=$(docker_ca_path); then
      run rm -f "$docker_ca"
      run rmdir "$(dirname "$docker_ca")" 2>/dev/null || true
    fi
    case "$(uname -s)" in
      Linux)
        local ca_destination
        ca_destination=$(linux_ca_destination)
        run rm -f "$ca_destination"
        refresh_linux_trust
        ;;
      Darwin)
        if (( DRY_RUN )); then
          show_cmd security delete-certificate -Z "$CA_SHA1" /Library/Keychains/System.keychain
        else
          security delete-certificate -Z "$CA_SHA1" /Library/Keychains/System.keychain >/dev/null 2>&1 || true
        fi
        ;;
    esac
    run rm -f "$SHARED_CA"
  fi
  echo "pkgreg client setup removed for project ${PROJECT}."
}

if [[ "$MODE" == uninstall ]]; then uninstall_client; else install_client; fi
`,
		p.Project, shellQuote(p.Project), shellQuote(p.Host), p.UnifiedPort, p.ProxyPort,
		shellQuote(p.SHA1), shellQuote(p.SHA256), shellQuote(pypiURL), shellQuote(npmURL),
		shellQuote(filesURL), shellQuote(proxyURL), p.PEM)
	return []byte(b.String()), nil
}

// PowerShell renders the Windows installer.
func PowerShell(cfg Config) ([]byte, error) {
	p, err := prepare(cfg)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by pkgreg for project %s.
# The embedded CA is public. This script never contains an API or write token.
[CmdletBinding()]
param(
  [switch]$DryRun,
  [switch]$Uninstall,
  [string]$HostName = %s,
  [string]$CacheIP = ""
)

$ErrorActionPreference = "Stop"
$Project = %s
$UnifiedPort = %d
$ProxyPort = %d
$CASha1 = %s
$CASha256 = %s
$CAPem = @'
%s'@

if ($HostName -notmatch '^[A-Za-z0-9][A-Za-z0-9.-]*$' -and $HostName -notmatch '^[0-9A-Fa-f:]+$') {
  throw "Invalid -HostName value"
}
if ($CacheIP -and $CacheIP -notmatch '^[0-9A-Fa-f:.]+$') {
  throw "Invalid -CacheIP value"
}
$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = [Security.Principal.WindowsPrincipal]::new($identity)
if (-not $DryRun -and -not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
  throw "Run this script explicitly from an Administrator PowerShell session."
}

$URLHost = if ($HostName.Contains(":")) { "[$HostName]" } else { $HostName }
$Authority = "${URLHost}:$UnifiedPort"
$InstallRoot = Join-Path $env:ProgramData "pkgreg\projects\$Project"
$SharedRoot = Join-Path $env:ProgramData "pkgreg\authorities"
$CAFile = Join-Path $SharedRoot "$CASha256.crt"
$StateFile = Join-Path $InstallRoot "state.json"
$HostsFile = Join-Path $env:SystemRoot "System32\drivers\etc\hosts"
$HostsMarker = "# pkgreg:$Project"
# uv's machine-level configuration. Windows has no directory of this project's own that uv
# would look in, so the file is shared, and one written by anyone else is left alone.
$UVConfig = Join-Path $env:ProgramData "uv\uv.toml"
$UVHeader = "# Generated by pkgreg for project $Project. Remove with -Uninstall."

function Show-Change([string]$Message) {
  Write-Host "+ $Message"
}

function Write-ManagedFile([string]$Path, [string]$Content) {
  if ($DryRun) { Show-Change "write $Path"; return }
  New-Item -ItemType Directory -Force -Path (Split-Path $Path) | Out-Null
  [IO.File]::WriteAllText($Path, $Content, [Text.UTF8Encoding]::new($false))
}

function Remove-ManagedFile([string]$Path) {
  if ($DryRun) { Show-Change "remove $Path"; return }
  Remove-Item -Force -ErrorAction SilentlyContinue $Path
}

function Set-HostsEntry([bool]$Install) {
  if ($DryRun) {
    if ($Install -and $CacheIP) { Show-Change "replace $HostsMarker in $HostsFile with $CacheIP $HostName" }
    else { Show-Change "remove $HostsMarker from $HostsFile" }
    return
  }
  $lines = @(Get-Content $HostsFile | Where-Object { -not $_.Contains($HostsMarker) })
  if ($Install -and $CacheIP) { $lines += "$CacheIP $HostName $HostsMarker" }
  [IO.File]::WriteAllLines($HostsFile, $lines)
}

# Every name here is set from Install-Client's table, and one the table leaves out is
# cleared: UV_INDEX_URL and UV_DEFAULT_INDEX, which an earlier version of this script set.
$EnvironmentNames = @(
  "PKGREG_PROJECT", "PKGREG_SERVER", "PKGREG_CA_FILE", "PKGREG_CA_SHA256",
  "PKGREG_DOCKER_REGISTRY", "PKGREG_GIT_URL",
  "PIP_CERT", "PIP_INDEX_URL", "UV_NATIVE_TLS", "UV_SYSTEM_CERTS",
  "UV_INDEX_URL", "UV_DEFAULT_INDEX",
  "NODE_EXTRA_CA_CERTS", "NPM_CONFIG_CAFILE", "NPM_CONFIG_REGISTRY",
  "PNPM_CONFIG_REGISTRY", "COREPACK_NPM_REGISTRY",
  "GIT_SSL_CAINFO", "PKGREG_FILES_URL", "PKGREG_APT_PROXY"
)

function Install-Client {
  $pypi = "https://${URLHost}:$UnifiedPort/$Project/pypi/root/pypi/+simple/"
  $npm = "https://${URLHost}:$UnifiedPort/$Project/npm/"
  $files = "https://${URLHost}:$UnifiedPort/$Project/files/"
  $aptProxy = "http://${URLHost}:$ProxyPort"
  if ($Project -ne "global") { $aptProxy = "http://${Project}@${URLHost}:$ProxyPort" }
  $values = @{
    PKGREG_PROJECT=$Project; PKGREG_SERVER="https://$Authority"
    PKGREG_CA_FILE=$CAFile; PKGREG_CA_SHA256=$CASha256
    PKGREG_DOCKER_REGISTRY=$Authority; PKGREG_GIT_URL="https://$Authority/$Project/git"
    PIP_CERT=$CAFile; PIP_INDEX_URL=$pypi; UV_NATIVE_TLS="true"; UV_SYSTEM_CERTS="true"
    NODE_EXTRA_CA_CERTS=$CAFile; NPM_CONFIG_CAFILE=$CAFile; NPM_CONFIG_REGISTRY=$npm
    PNPM_CONFIG_REGISTRY=$npm; COREPACK_NPM_REGISTRY=$npm.TrimEnd("/")
    GIT_SSL_CAINFO=$CAFile; PKGREG_FILES_URL=$files; PKGREG_APT_PROXY=$aptProxy
  }

  if ($DryRun) {
    Show-Change "write embedded CA to $CAFile"
    Show-Change "import CA SHA-256 $CASha256 into LocalMachine\Root"
    foreach ($name in $EnvironmentNames) { Show-Change "set machine environment $name" }
  } else {
    New-Item -ItemType Directory -Force -Path $InstallRoot, $SharedRoot | Out-Null
    if (-not (Test-Path $StateFile)) {
      $previous = @{}
      foreach ($name in $EnvironmentNames) {
        $previous[$name] = [Environment]::GetEnvironmentVariable($name, "Machine")
      }
      @{ PreviousEnvironment=$previous; CASha256=$CASha256; Authority=$Authority } |
        ConvertTo-Json -Depth 4 | Set-Content -Encoding UTF8 $StateFile
    }
    [IO.File]::WriteAllText($CAFile, $CAPem, [Text.UTF8Encoding]::new($false))
    # The .NET store rather than the Cert: drive and Import-Certificate. Both of those
    # come from modules that are normally auto-loaded and are not always: on a runner
    # with a trimmed PSModulePath the provider never registers, and the script dies with
    # "A drive with the name 'Cert' does not exist" after having already written files.
    # X509Store is in the base runtime on both PowerShell 5.1 and 7, so it cannot go
    # missing.
    $store = [Security.Cryptography.X509Certificates.X509Store]::new("Root", "LocalMachine")
    $store.Open("ReadWrite")
    try {
      $already = @($store.Certificates | Where-Object Thumbprint -eq $CASha1)
      if ($already.Count -eq 0) {
        $store.Add([Security.Cryptography.X509Certificates.X509Certificate2]::new($CAFile))
      }
    } finally {
      $store.Close()
    }
    foreach ($name in $EnvironmentNames) {
      [Environment]::SetEnvironmentVariable($name, [string]$values[$name], "Machine")
    }
  }
  # uv's pip interface, and nothing else. UV_INDEX_URL at machine scope reached uv's
  # project commands as well: uv lock and uv sync rewrote uv.lock to name this cache, a
  # lock no other machine can use, and uv sync --locked refused one made against PyPI. uv
  # reads a [pip] table for uv pip alone.
  $uvContent = @"
$UVHeader
[pip]
index-url = "$pypi"

"@
  $uvOurs = -not (Test-Path $UVConfig)
  if (-not $uvOurs) {
    $uvOurs = [string](Get-Content -TotalCount 1 $UVConfig) -like "# Generated by pkgreg for project *"
  }
  if ($uvOurs) {
    Write-ManagedFile $UVConfig $uvContent
  } else {
    Write-Host ('note: {0} stays in charge of uv on this machine; for uv pip to use the cache, add index-url = "{1}" to its [pip] table' -f $UVConfig, $pypi)
  }
  Set-HostsEntry $true
  Write-Host "pkgreg client setup installed for project $Project."
  Write-Host "Open a new terminal to activate tool settings. CA SHA-256: $CASha256"
  # Docker Desktop for Windows takes registry trust from the Windows certificate store,
  # which the import above populated. It does not read a certs.d directory: that path
  # would have to be named <host>:<port>, and a colon cannot appear in a Windows path.
  Write-Host "Restart Docker Desktop so it picks up the imported certificate."
}

function Uninstall-Client {
  Set-HostsEntry $false
  $state = $null
  if (Test-Path $StateFile) { $state = Get-Content -Raw $StateFile | ConvertFrom-Json }
  if ($DryRun) {
    Show-Change "restore machine tool environment from $StateFile"
  } elseif ($state) {
    foreach ($name in $EnvironmentNames) {
      $old = $state.PreviousEnvironment.$name
      [Environment]::SetEnvironmentVariable($name, $old, "Machine")
    }
  }
  Remove-ManagedFile $StateFile
  if (-not $DryRun) { Remove-Item -Force -Recurse -ErrorAction SilentlyContinue $InstallRoot }
  # Only this project's: another project installed since owns the file now.
  if ((Test-Path $UVConfig) -and [string](Get-Content -TotalCount 1 $UVConfig) -eq $UVHeader) {
    Remove-ManagedFile $UVConfig
  }

  $other = @(Get-ChildItem (Join-Path $env:ProgramData "pkgreg\projects") -Filter state.json -Recurse -ErrorAction SilentlyContinue |
    Where-Object FullName -ne $StateFile |
    Where-Object { (Get-Content -Raw $_.FullName | ConvertFrom-Json).CASha256 -eq $CASha256 })
  if ($other.Count -eq 0) {
    if ($DryRun) {
      Show-Change "remove CA $CASha1 from LocalMachine\Root"
    } else {
      $store = [Security.Cryptography.X509Certificates.X509Store]::new("Root", "LocalMachine")
      $store.Open("ReadWrite")
      try {
        $store.Certificates | Where-Object Thumbprint -eq $CASha1 | ForEach-Object { $store.Remove($_) }
      } finally {
        $store.Close()
      }
    }
    Remove-ManagedFile $CAFile
  }
  Write-Host "pkgreg client setup removed for project $Project."
}

if ($Uninstall) { Uninstall-Client } else { Install-Client }
`,
		p.Project, psQuote(p.Host), psQuote(p.Project), p.UnifiedPort, p.ProxyPort,
		psQuote(p.SHA1), psQuote(p.SHA256), p.PEM)
	return []byte(strings.ReplaceAll(b.String(), "\n", "\r\n")), nil
}
